- hosts: legacy
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python and Git
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - git

